export const colors = {
  gray: "§7",
  white: "§f",
  red: "§c",
  green: "§a",
  reset: "§r",
};

export const rules = {
  max: 6,
  checktime: 100,
  spamwait: 20,
};

export const foods = new Set([
  "minecraft:apple",
  "minecraft:bread",
  "minecraft:cooked_beef",
  "minecraft:cooked_chicken",
  "minecraft:cooked_porkchop",
  "minecraft:potion",
  "minecraft:water_bottle",
  "minecraft:milk_bucket",
  "minecraft:baked_potato",
  "minecraft:beetroot",
  "minecraft:beetroot_soup",
  "minecraft:cake",
  "minecraft:carrot",
  "minecraft:chorus_fruit",
  "minecraft:cooked_cod",
  "minecraft:cooked_mutton",
  "minecraft:cooked_rabbit",
  "minecraft:cooked_salmon",
  "minecraft:cookie",
  "minecraft:dried_kelp",
  "minecraft:enchanted_golden_apple",
  "minecraft:golden_apple",
  "minecraft:glow_berries",
  "minecraft:golden_carrot",
  "minecraft:honey_bottle",
  "minecraft:melon_slice",
  "minecraft:mushroom_stew",
  "minecraft:poisonous_potato",
  "minecraft:potato",
  "minecraft:pufferfish",
  "minecraft:pumpkin_pie",
  "minecraft:rabbit_stew",
  "minecraft:beef",
  "minecraft:chicken",
  "minecraft:cod",
  "minecraft:mutton",
  "minecraft:porkchop",
  "minecraft:rabbit",
  "minecraft:salmon",
  "minecraft:rotten_flesh",
  "minecraft:spider_eye",
  "minecraft:suspicious_stew",
  "minecraft:sweet_berries",
  "minecraft:tropical_fish",
  "addon:dunlin_donuts",
  "addon:kfc",
  "addon:m1",
  "addon:m2",
  "addon:m3",
  "addon:McDonald",
  "addon:su1",
  "addon:su2",
  "addon:the_coffee_bean",
  "addon:cooked_axolotl_bucket",
  "addon:co",
  "addon:sp_1",
  "addon:sp_2",
  "addon:sp_3",
  "addon:sp_4",
]);
