const CONFIG = {
  defaultIdleSeconds: 300,
  warningSeconds: 5,
  movementTolerance: 0.15,
  rotationTolerance: 3.0,
  focusHeight: 1.35,
  cinematicFov: 30,
  minIdleSeconds: 10,
  maxIdleSeconds: 900,
  collisionStep: 0.45,
  collisionBuffer: 0.2,
  schedulerBudget: 4,
  blockCacheMax: 1024,
  blockCacheTTL: 400,
};

const PASS_THROUGH_BLOCKS = new Set([
  "minecraft:air",
  "minecraft:cave_air",
  "minecraft:void_air",
  "minecraft:water",
  "minecraft:flowing_water",
  "minecraft:lava",
  "minecraft:flowing_lava",
  "minecraft:short_grass",
  "minecraft:tall_grass",
  "minecraft:fern",
  "minecraft:large_fern",
  "minecraft:deadbush",
  "minecraft:vine",
  "minecraft:glow_lichen",
  "minecraft:seagrass",
  "minecraft:tall_seagrass",
  "minecraft:snow_layer",
]);

const SHOT_LIBRARY = [
  // ─── CLOSE-UP ──────────────────────────────────────────────────────────────
  {
    id: "close-low",
    yawOffset: 15,
    distance: 2.8,
    height: 0.6,
    slide: 0.02,
    bob: 0.015,
    duration: 100,
    targetUp: 1.7,
  },
  {
    id: "close-front",
    yawOffset: 0,
    distance: 2.2,
    height: 1.6,
    slide: 0.02,
    bob: 0.02,
    duration: 90,
    targetUp: 1.5,
  },
  {
    id: "close-left",
    yawOffset: -60,
    distance: 2.5,
    height: 1.5,
    slide: 0.03,
    bob: 0.02,
    duration: 95,
    targetUp: 1.5,
  },
  {
    id: "close-right",
    yawOffset: 60,
    distance: 2.5,
    height: 1.5,
    slide: 0.03,
    bob: 0.02,
    duration: 95,
    targetUp: 1.5,
  },
  {
    id: "close-back",
    yawOffset: 180,
    distance: 2.7,
    height: 1.6,
    slide: 0.02,
    bob: 0.02,
    duration: 100,
    targetUp: 1.5,
  },
  {
    id: "orbit-close",
    yawOffset: 45,
    distance: 3.2,
    height: 1.7,
    slide: 0.06,
    bob: 0.02,
    duration: 95,
    targetUp: 1.5,
  },

  // ─── HERO / MEDIUM ─────────────────────────────────────────────────────────
  {
    id: "hero-low",
    yawOffset: -18,
    distance: 4.9,
    height: 0.75,
    slide: 0.04,
    bob: 0.02,
    duration: 105,
    targetUp: 1.72,
  },
  {
    id: "dutch-hero",
    yawOffset: 52,
    distance: 6.8,
    height: 1.3,
    slide: 0.05,
    bob: 0.025,
    duration: 100,
    targetUp: 1.65,
  },
  {
    id: "hero-center",
    yawOffset: 8,
    distance: 4.0,
    height: 1.5,
    slide: 0.04,
    bob: 0.025,
    duration: 110,
    targetUp: 1.58,
  },
  {
    id: "front-medium",
    yawOffset: 32,
    distance: 4.8,
    height: 1.85,
    slide: 0.05,
    bob: 0.03,
    duration: 100,
    targetUp: 1.45,
  },
  {
    id: "profile",
    yawOffset: 88,
    distance: 4.6,
    height: 1.9,
    slide: 0.06,
    bob: 0.03,
    duration: 95,
    targetUp: 1.45,
    targetRight: 0.3,
  },
  {
    id: "over-shoulder",
    yawOffset: 146,
    distance: 3.9,
    height: 1.8,
    slide: 0.03,
    bob: 0.02,
    duration: 95,
    targetUp: 1.45,
    targetForward: 2.8,
    targetRight: -0.8,
  },
  {
    id: "rear-hero",
    yawOffset: 175,
    distance: 5.6,
    height: 1.55,
    slide: 0.03,
    bob: 0.02,
    duration: 100,
    targetUp: 1.45,
    targetForward: 4.6,
  },
  {
    id: "medium-back",
    yawOffset: -140,
    distance: 5.2,
    height: 1.7,
    slide: 0.04,
    bob: 0.025,
    duration: 100,
    targetUp: 1.5,
  },
  {
    id: "medium-orbit",
    yawOffset: 120,
    distance: 5.5,
    height: 2.0,
    slide: 0.07,
    bob: 0.03,
    duration: 110,
    targetUp: 1.5,
  },
  {
    id: "medium-top",
    yawOffset: 0,
    distance: 4.5,
    height: 4.0,
    slide: 0.03,
    bob: 0.03,
    duration: 105,
    targetUp: 1.2,
  },

  // ─── TRACKING / FOLLOW ─────────────────────────────────────────────────────
  {
    id: "tracking-follow",
    yawOffset: 0,
    distance: 7,
    height: 1.8,
    slide: 0.18,
    bob: 0.02,
    duration: 220,
    targetUp: 1.45,
    followVelocity: true,
  },
  {
    id: "side-tracking",
    yawOffset: 90,
    distance: 8,
    height: 2,
    slide: 0.22,
    bob: 0.025,
    duration: 210,
    targetUp: 1.45,
    followVelocity: true,
  },
  {
    id: "peek-shot",
    yawOffset: 70,
    distance: 5,
    height: 1.8,
    slide: 0.04,
    bob: 0.02,
    duration: 120,
    targetUp: 1.5, // ✏️
    targetRight: 1.5,
    followVelocity: true,
  },

  // ─── WIDE / ESTABLISHING ───────────────────────────────────────────────────
  {
    id: "hero-wide",
    yawOffset: -40,
    distance: 8.9,
    height: 3.1,
    slide: 0.08,
    bob: 0.035,
    duration: 125,
    targetUp: 1.45,
  },
  {
    id: "orbit-wide",
    yawOffset: -45,
    distance: 9.5,
    height: 3.2,
    slide: 0.08,
    bob: 0.03,
    duration: 120,
    targetUp: 1.45,
  },
  {
    id: "side-silhouette",
    yawOffset: -92,
    distance: 9.8,
    height: 2.4,
    slide: 0.05,
    bob: 0.03,
    duration: 110,
    targetUp: 1.5,
  },
  {
    id: "centered-wide",
    yawOffset: -158,
    distance: 10.4,
    height: 3.5,
    slide: 0.05,
    bob: 0.03,
    duration: 120,
    targetUp: 1.45,
  },
  {
    id: "low-wide",
    yawOffset: 25,
    distance: 10.5,
    height: 0.8,
    slide: 0.07,
    bob: 0.03,
    duration: 120,
    targetUp: 1.8,
  },
  {
    id: "cinematic-front",
    yawOffset: 0,
    distance: 11.5,
    height: 2.8,
    slide: 0.06,
    bob: 0.03,
    duration: 130,
    targetUp: 1.4,
  },
  {
    id: "sweep-side",
    yawOffset: 90,
    distance: 13,
    height: 2.2,
    slide: 0.16,
    bob: 0.025,
    duration: 160,
    targetUp: 1.5,
  },
  {
    id: "cinematic-back",
    yawOffset: 170,
    distance: 12.0,
    height: 2.5,
    slide: 0.06,
    bob: 0.03,
    duration: 130,
    targetUp: 1.4,
  },
  {
    id: "cinema-orbit",
    yawOffset: 120,
    distance: 11,
    height: 2.8,
    slide: 0.14,
    bob: 0.025,
    duration: 180,
    targetUp: 1.45,
  },
  {
    id: "spiral-rise",
    yawOffset: 140,
    distance: 10,
    height: 1.5,
    slide: 0.15,
    bob: 0.04,
    duration: 180,
    targetUp: 1.4,
  },
  {
    id: "slow-push",
    yawOffset: 0,
    distance: 16,
    height: 2.0,
    slide: -0.12,
    bob: 0.015,
    duration: 190,
    targetUp: 1.45,
  },

  // ─── AERIAL / DRONE ────────────────────────────────────────────────────────
  {
    id: "tower-shot",
    yawOffset: 18,
    distance: 7.2,
    height: 8.5,
    slide: 0.04,
    bob: 0.03,
    duration: 105,
    targetUp: 1.2,
  },
  {
    id: "sky-orbit",
    yawOffset: 90,
    distance: 6.0,
    height: 12.0,
    slide: 0.08,
    bob: 0.04,
    duration: 120,
    targetUp: 1.2,
  },
  {
    id: "drone-pass",
    yawOffset: 35,
    distance: 14,
    height: 4.5,
    slide: 0.18,
    bob: 0.02,
    duration: 170,
    targetUp: 1.45,
  },
  {
    id: "far-side",
    yawOffset: 90,
    distance: 16.0,
    height: 6.0,
    slide: 0.09,
    bob: 0.04,
    duration: 135,
    targetUp: 1.4,
  },
  {
    id: "far-back",
    yawOffset: 180,
    distance: 14.0,
    height: 5.0,
    slide: 0.08,
    bob: 0.035,
    duration: 130,
    targetUp: 1.4,
  },
  {
    id: "far-establishing",
    yawOffset: 126,
    distance: 15.5,
    height: 7.2,
    slide: 0.1,
    bob: 0.04,
    duration: 135,
    targetUp: 1.35,
  },
  {
    id: "flyover",
    yawOffset: -70,
    distance: 18,
    height: 9,
    slide: 0.22,
    bob: 0.03,
    duration: 200,
    targetUp: 1.3,
  },
  {
    id: "epic-overlook",
    yawOffset: -112,
    distance: 18.5,
    height: 10.8,
    slide: 0.1,
    bob: 0.04,
    duration: 145,
    targetUp: 1.35,
  },
  {
    id: "top-down",
    yawOffset: 180,
    distance: 0,
    height: 14.5,
    slide: 0.03,
    bob: 0.05,
    duration: 95,
    targetUp: 1.1, // ✏️
  },

  // ─── CINEMATIC MOTION (arc / push / pull / rise) ───────────────────────────
  {
    id: "dramatic-push",
    distance: 16,
    endDistance: 5,
    height: 2,
    slide: 0.04,
    bob: 0.02,
    duration: 120,
    targetUp: 1.5, // ✏️
    yawOffset: 0,
    followVelocity: true,
  },
  {
    id: "reveal-pull",
    distance: 5,
    endDistance: 18,
    height: 2,
    slide: 0.04,
    bob: 0.02,
    duration: 120,
    targetUp: 1.5, // ✏️
    yawOffset: 0,
    followVelocity: true,
  },
  {
    id: "arc-reveal",
    yawOffset: -40,
    distance: 7,
    height: 2,
    arc: 90,
    slide: 0.05,
    bob: 0.02,
    duration: 120,
    targetUp: 1.5, // ✏️
    followVelocity: true,
  },
  {
    id: "environment-reveal",
    distance: 8,
    height: 3,
    targetForward: 8,
    targetUp: 4,
    slide: 0.05,
    bob: 0.025,
    duration: 120, // ✏️
    followVelocity: true,
  },
  {
    id: "vertical-orbit",
    yawOffset: 0,
    distance: 10,
    height: 4,
    startHeight: 1,
    endHeight: 8,
    arc: 180,
    slide: 0.06,
    bob: 0.03,
    duration: 120,
    targetUp: 1.5, // ✏️
    followVelocity: true,
  },
  {
    id: "ascending-drone",
    yawOffset: 0,
    distance: 12,
    height: 8,
    startHeight: 2,
    endHeight: 15,
    slide: 0.06,
    bob: 0.03,
    duration: 120,
    targetUp: 1.5, // ✏️
    followVelocity: true,
  },

  // ─── MEGA / SIGNATURE ──────────────────────────────────────────────────────
  {
    id: "mega-establishing",
    yawOffset: 0,
    distance: 35,
    height: 18,
    slide: 0.3,
    bob: 0.04,
    duration: 260,
    targetUp: 1.5, // ✏️
    followVelocity: true,
  },
];

export { CONFIG, PASS_THROUGH_BLOCKS, SHOT_LIBRARY };
