const biomeIdList = {
  "minecraft:the_end": "§dThe End",
  "minecraft:overworld": "§aOverworld",
  "minecraft:nether": "§cThe Nether",

  "minecraft:ocean": "Ocean",
  "minecraft:legacy_frozen_ocean": "Legacy Frozen Ocean",
  "minecraft:deep_ocean": "Deep Ocean",
  "minecraft:frozen_ocean": "Frozen Ocean",
  "minecraft:deep_frozen_ocean": "Deep Frozen Ocean",
  "minecraft:cold_ocean": "Cold Ocean",
  "minecraft:deep_cold_ocean": "Deep Cold Ocean",
  "minecraft:lukewarm_ocean": "Lukewarm Ocean",
  "minecraft:deep_lukewarm_ocean": "Deep Lukewarm Ocean",
  "minecraft:warm_ocean": "Warm Ocean",
  "minecraft:deep_warm_ocean": "Deep Warm Ocean",
  "minecraft:river": "River",
  "minecraft:frozen_river": "Frozen River",
  "minecraft:beach": "Beach",
  "minecraft:stone_beach": "Stony Shore",
  "minecraft:cold_beach": "Snowy Beach",
  "minecraft:forest": "Forest",
  "minecraft:forest_hills": "Wooded Hills",
  "minecraft:flower_forest": "Flower Forest",
  "minecraft:birch_forest": "Birch Forest",
  "minecraft:birch_forest_hills": "Birch Forest Hills",
  "minecraft:birch_forest_mutated": "Old Growth Birch Forest",
  "minecraft:birch_forest_hills_mutated": "Tall Birch Hills",
  "minecraft:roofed_forest": "Dark Forest",
  "minecraft:roofed_forest_mutated": "Dark Forest Hills",
  "minecraft:pale_garden": "Pale Garden",
  "minecraft:jungle": "Jungle",
  "minecraft:jungle_hills": "Jungle Hills",
  "minecraft:jungle_mutated": "Modified Jungle",
  "minecraft:jungle_edge": "Sparse Jungle",
  "minecraft:jungle_edge_mutated": "Modified Jungle Edge",
  "minecraft:bamboo_jungle": "Bamboo Jungle",
  "minecraft:bamboo_jungle_hills": "Bamboo Jungle Hills",
  "minecraft:taiga": "Taiga",
  "minecraft:taiga_hills": "Taiga Hills",
  "minecraft:taiga_mutated": "Taiga Mountains",
  "minecraft:cold_taiga": "Snowy Taiga",
  "minecraft:cold_taiga_hills": "Snowy Taiga Hills",
  "minecraft:cold_taiga_mutated": "Snowy Taiga Mountains",
  "minecraft:mega_taiga": "Old Growth Pine Taiga",
  "minecraft:mega_taiga_hills": "Giant Tree Taiga Hills",
  "minecraft:redwood_taiga_mutated": "Old Growth Spruce Taiga",
  "minecraft:redwood_taiga_hills_mutated": "Giant Spruce Taiga Hills",
  "minecraft:mushroom_island": "Mushroom Fields",
  "minecraft:mushroom_island_shore": "Mushroom Field Shore",
  "minecraft:swampland": "Swamp",
  "minecraft:swampland_mutated": "Swamp Hills",
  "minecraft:mangrove_swamp": "Mangrove Swamp",
  "minecraft:savanna": "Savanna",
  "minecraft:savanna_plateau": "Savanna Plateau",
  "minecraft:savanna_mutated": "Windswept Savanna",
  "minecraft:savanna_plateau_mutated": "Shattered Savanna Plateau",
  "minecraft:plains": "Plains",
  "minecraft:sunflower_plains": "Sunflower Plains",
  "minecraft:desert": "Desert",
  "minecraft:desert_hills": "Desert Hills",
  "minecraft:desert_mutated": "Desert Lakes",
  "minecraft:ice_plains": "Snowy Plains",
  "minecraft:ice_mountains": "Snowy Mountains",
  "minecraft:ice_plains_spikes": "Ice Spikes",
  "minecraft:extreme_hills": "Windswept Hills",
  "minecraft:extreme_hills_plus_trees": "Windswept Forest",
  "minecraft:extreme_hills_mutated": "Windswept Gravelly Hills",
  "minecraft:extreme_hills_plus_trees_mutated": "Modified Gravelly Mountains",
  "minecraft:extreme_hills_edge": "Mountain Edge",
  "minecraft:mesa": "Badlands",
  "minecraft:mesa_plateau": "Badlands Plateau",
  "minecraft:mesa_plateau_mutated": "Modified Badlands Plateau",
  "minecraft:mesa_plateau_stone": "Wooded Badlands",
  "minecraft:mesa_plateau_stone_mutated": "Modified Wooded Badlands Plateau",
  "minecraft:mesa_bryce": "Eroded Badlands",
  "minecraft:meadow": "Meadow",
  "minecraft:cherry_grove": "Cherry Grove",
  "minecraft:grove": "Grove",
  "minecraft:snowy_slopes": "Snowy Slopes",
  "minecraft:jagged_peaks": "Jagged Peaks",
  "minecraft:frozen_peaks": "Frozen Peaks",
  "minecraft:stony_peaks": "Stony Peaks",
  "minecraft:lush_caves": "Lush Caves",
  "minecraft:dripstone_caves": "Dripstone Caves",
  "minecraft:deep_dark": "Deep Dark",
  "minecraft:hell": "Nether Wastes",
  "minecraft:crimson_forest": "Crimson Forest",
  "minecraft:warped_forest": "Warped Forest",
  "minecraft:soulsand_valley": "Soul Sand Valley",
  "minecraft:basalt_deltas": "Basalt Deltas",
};

const EXCLUDED_BIOMES = new Set(["minecraft:the_end"]);
const Colors = {
  gold: "§6",
  white: "§f",
  gray: "§7",
};

export { biomeIdList, EXCLUDED_BIOMES, Colors };
