export const armorData = {
  "minecraft:leather_helmet": { armor: 1, toughness: 0, slot: "Head", maxReduction: 28 },
  "minecraft:leather_chestplate": { armor: 3, toughness: 0, slot: "Chest", maxReduction: 28 },
  "minecraft:leather_leggings": { armor: 2, toughness: 0, slot: "Legs", maxReduction: 28 },
  "minecraft:leather_boots": { armor: 1, toughness: 0, slot: "Feet", maxReduction: 28 },
  "minecraft:golden_helmet": { armor: 2, toughness: 0, slot: "Head", maxReduction: 44 },
  "minecraft:golden_chestplate": { armor: 5, toughness: 0, slot: "Chest", maxReduction: 44 },
  "minecraft:golden_leggings": { armor: 3, toughness: 0, slot: "Legs", maxReduction: 44 },
  "minecraft:golden_boots": { armor: 1, toughness: 0, slot: "Feet", maxReduction: 44 },
  "minecraft:chainmail_helmet": { armor: 2, toughness: 0, slot: "Head", maxReduction: 48 },
  "minecraft:chainmail_chestplate": { armor: 5, toughness: 0, slot: "Chest", maxReduction: 48 },
  "minecraft:chainmail_leggings": { armor: 4, toughness: 0, slot: "Legs", maxReduction: 48 },
  "minecraft:chainmail_boots": { armor: 1, toughness: 0, slot: "Feet", maxReduction: 48 },
  "minecraft:iron_helmet": { armor: 2, toughness: 0, slot: "Head", maxReduction: 60 },
  "minecraft:iron_chestplate": { armor: 6, toughness: 0, slot: "Chest", maxReduction: 60 },
  "minecraft:iron_leggings": { armor: 5, toughness: 0, slot: "Legs", maxReduction: 60 },
  "minecraft:iron_boots": { armor: 2, toughness: 0, slot: "Feet", maxReduction: 60 },
  "minecraft:diamond_helmet": { armor: 3, toughness: 2, slot: "Head", maxReduction: 80 },
  "minecraft:diamond_chestplate": { armor: 8, toughness: 2, slot: "Chest", maxReduction: 80 },
  "minecraft:diamond_leggings": { armor: 6, toughness: 2, slot: "Legs", maxReduction: 80 },
  "minecraft:diamond_boots": { armor: 3, toughness: 2, slot: "Feet", maxReduction: 80 },
  "minecraft:netherite_helmet": { armor: 3, toughness: 3, slot: "Head", maxReduction: 80 },
  "minecraft:netherite_chestplate": { armor: 8, toughness: 3, slot: "Chest", maxReduction: 80 },
  "minecraft:netherite_leggings": { armor: 6, toughness: 3, slot: "Legs", maxReduction: 80 },
  "minecraft:netherite_boots": { armor: 3, toughness: 3, slot: "Feet", maxReduction: 80 },
  "minecraft:turtle_shell": { armor: 2, toughness: 0, slot: "Head", maxReduction: 28 },
};
